site_name: Woo Stream - Facebook live stream integration for WooCommerce.

nav:
  - Getting Started:
    - Introduction: index.md
    - Shortcodes: shortcodes.md
    - Requests Page: requests.md
  - User Guide:
    - Create Facebook App: create-app.md
    - Get Short Lived Token: get-token.md
    - Account Settings: account-settings.md
  - Support: support.md

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme)" # Automatic mode
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic:
      mode: view

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XeCreators
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/XeCreators
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/xecreatorsit
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/XeCreators
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/xecreators/